name: CI

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  test-ubuntu:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - name: Make dictu and run tests (No HTTP)
        run: |
          make debug DISABLE_HTTP=1
          ./dictu tests/runTests.du | tee /dev/stderr | grep -q 'Total memory usage: 0'
      - name: Remove build directory
        run: |
          rm -rf build
      - name: Make dictu and run tests (HTTP)
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
          make debug
          ./dictu tests/runTests.du | tee /dev/stderr | grep -q 'Total memory usage: 0'
  test-mac:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Make dictu and run tests (No HTTP)
        run: |
          make debug DISABLE_HTTP=1
          ./dictu tests/runTests.du | tee /dev/stderr | grep -q 'Total memory usage: 0'
      - name: Remove build directory
        run: |
          rm -rf build
      - name: Make dictu and run tests
        run: |
          make debug
          ./dictu tests/runTests.du | tee /dev/stderr | grep -q 'Total memory usage: 0'

  test-windows:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Make dictu and run tests (No HTTP)
        run: |
          make debug DISABLE_HTTP=1
          .\dictu tests\runTests.du | tee \dev\stderr | grep -q 'Total memory usage: 0'
      - name: Remove build directory
        run: |
          rm -rf build
      - name: Make dictu and run tests
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
          make debug
          .\dictu tests\runTests.du | tee \dev\stderr | grep -q 'Total memory usage: 0'

